version: "3.7"
services:
  ns:
    image: "coredns/coredns"
    volumes:
      - ./Corefile:/Corefile:ro
    ports:
      - "5353:5353/udp"
      - "5353:5353"
  doh:
    image: doh_proxy
    expose:
      - 3000
    command: ["/doh-proxy", "-u", "ns:5353", "-l", "0.0.0.0:3000"]
  nginx:
    image: nginx_letsencrypt
    environment:
      - "UPSTREAM_SERVER=http://doh:3000"
      - "HOST=doh.ndieff.dev"
      - "EMAIL=nick.dieff@gmail.com"
    ports:
      - "80:80"
      - "443:443"


